import { test } from 'node:test';
import assert from 'node:assert/strict';
import { analyzeAudioFrame, extractAudioMeasurement } from './audio.ts';
import { AmbientCalibrator } from './audioCalibration.ts';
import { validateRecord } from '../contracts/index.ts';
const wave = (hz: number, amplitude = 0.2) => Float32Array.from({ length: 4096 }, (_, i) => amplitude * Math.sin(i / 48000 * hz * Math.PI * 2));
test('canonical PCM extractor measures known tone, rejects invalid PCM and serializes valid provenance', () => {
  const pcm = wave(220);
  const measured = analyzeAudioFrame(pcm, 48000);
  assert.ok(Math.abs(measured.pitchHz! - 220) < 1);
  assert.ok(Math.abs(measured.centroidHz! - 220) < 5);
  assert.ok(Math.abs(measured.dbfs - 20 * Math.log10(0.2 / Math.sqrt(2))) < 0.1);
  assert.equal(analyzeAudioFrame(new Float32Array(4096), 48000).pitchHz, null);
  assert.throws(() => analyzeAudioFrame(Float32Array.from([NaN]), 48000));
  const record = extractAudioMeasurement(pcm, 48000, { id: 'm1', observationId: 'o1', artifactId: 'a1', startMs: 0, sourceKind: 'engine-generated', timebase: { clockId: 'pcm', origin: 'session-start', unit: 'ms', referenceClockId: null, offsetToReferenceMs: null, syncUncertaintyMs: 0 } });
  assert.equal(validateRecord(record).valid, true);
  assert.equal(record.measurements.find(m => m.name === 'pitchHz')!.value, measured.pitchHz);
});
test('ambient calibration waits for quiet windows, does not absorb singing, and flags clipping', () => {
  const calibrator = new AmbientCalibrator();
  const singing = wave(220);
  let result = calibrator.update(analyzeAudioFrame(singing, 48000), singing, 0);
  for (let i = 1; i < 35; i++) result = calibrator.update(analyzeAudioFrame(singing, 48000), singing, i * 100);
  assert.equal(result.state, 'collecting');
  let seed = 123;
  const quiet = Float32Array.from({ length: 4096 }, () => { seed = (1664525 * seed + 1013904223) >>> 0; return (seed / 2 ** 32 - 0.5) * 0.003; });
  for (let i = 35; i < 60; i++) result = calibrator.update(analyzeAudioFrame(quiet, 48000), quiet, i * 100);
  assert.equal(result.state, 'ready');
  assert.ok(result.noiseFloorDbfs! < -55);
  result = calibrator.update(analyzeAudioFrame(singing, 48000), singing, 6100);
  assert.ok(result.snrDb! > 35);
  const clipped = new Float32Array(4096).fill(1);
  assert.equal(calibrator.update(analyzeAudioFrame(clipped, 48000), clipped, 6200).clipping, true);
});
