import { useCallback, useEffect, useRef, useState } from 'react'
import type { TrackingFrame } from '../../types'
import type { MotionObservation, MotionMarker } from '../../contracts/learning'
import { validateLearningRecord } from '../../contracts/learning'
import { motionSample, observedEnvelope, phaseAt } from '../../capture/motion'
import './MotionCapturePanel.css'
const save=(blob:Blob,name:string)=>{const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
export function MotionCapturePanel({frame,videoStream,audioStream}:{frame:TrackingFrame|null;videoStream?:MediaStream|null;audioStream?:MediaStream|null}){
 const [active,setActive]=useState(false),[elapsed,setElapsed]=useState(0),[record,setRecord]=useState<MotionObservation|null>(null),[index,setIndex]=useState(0),[media,setMedia]=useState<Blob|null>(null),[mediaUrl,setMediaUrl]=useState(''),[error,setError]=useState(''),[gesture,setGesture]=useState('Comfortable ah, then relax'),[context,setContext]=useState('seated; comfortable effort'),[count,setCount]=useState(0)
 const draft=useRef<MotionObservation|null>(null),recorder=useRef<MediaRecorder|null>(null),player=useRef<HTMLVideoElement|null>(null)
 const finish=useCallback((stopped=false)=>{const current=draft.current;if(!current)return;const t=performance.now()-current.timebase.originMs;const phase=phaseAt(t);current.markers.push({captureMs:t,repetition:phase.repetition,phase:phase.phase,type:stopped?'stop':'task-end',source:stopped?'user':'protocol',note:stopped?'Stopped early; retain incomplete attempt':'Capture ended'});current.observedEnvelope=observedEnvelope(current.samples);setRecord(structuredClone(current));draft.current=null;setActive(false);setIndex(0);if(recorder.current?.state==='recording')recorder.current.stop()},[])
 useEffect(()=>{if(!active)return;const timer=window.setInterval(()=>{const current=draft.current;if(!current)return;const t=performance.now()-current.timebase.originMs;setElapsed(t);const p=phaseAt(t);if(p.done){finish();return}const prior=current.markers.filter(m=>m.type==='phase').at(-1);if(!prior||prior.phase!==p.phase||prior.repetition!==p.repetition)current.markers.push({captureMs:t,repetition:p.repetition,phase:p.phase,type:'phase',source:'protocol',note:p.phase==='gesture'?gesture:p.phase==='return'?'Return comfortably':'Neutral baseline'})},50);return()=>clearInterval(timer)},[active,gesture,finish])
 useEffect(()=>{const current=draft.current;if(!current||!frame||frame.timestamp<current.timebase.originMs)return;const previous=current.samples.at(-1);if(previous&&frame.timestamp<=previous.sourceTimestampMs)return;const p=phaseAt(frame.timestamp-current.timebase.originMs);if(p.done)return;current.samples.push(motionSample(frame,current.timebase.originMs,p.repetition,p.phase,previous?.sourceTimestampMs));setCount(current.samples.length)},[frame])
 useEffect(()=>()=>{if(recorder.current?.state==='recording')recorder.current.stop()},[])
 useEffect(()=>()=>{if(mediaUrl)URL.revokeObjectURL(mediaUrl)},[mediaUrl])
 const start=()=>{
  if(!videoStream?.getVideoTracks().some(t=>t.readyState==='live')){setError('Start the camera before capturing real motion. Demo frames are not captured.');return}
  setError('');setMedia(null);setMediaUrl('');setRecord(null);setElapsed(0);setCount(0)
  const now=performance.now(),id=crypto.randomUUID()
  const next:MotionObservation={schemaVersion:'1.0.0',kind:'motion-observation',id,createdAt:new Date().toISOString(),provenance:{kind:'derived-measurement',producer:'browser-motion-capture',producerVersion:'1.0.0',sourceIds:[id+'-camera'],sourceHashes:[]},attemptId:id,cueId:'user-selected-visible-gesture',cueVersion:'1',context:{gesture,description:context},samples:[],markers:[{captureMs:0,repetition:1,phase:'neutral',type:'task-start',source:'protocol',note:'Three comfortable neutral → gesture → return repetitions'},{captureMs:0,repetition:1,phase:'neutral',type:'cue-delivery',source:'protocol',note:gesture}],coordinateFrame:'normalized-image-and-outer-eye-relative-2d',timebase:{clock:'browser-performance',originMs:now,syncUncertaintyMs:null},visibility:'Per-point visibility; absent callbacks appear as timing gaps. Hidden surfaces are unobserved.',uncertainty:'unquantified-image-estimates',observedEnvelope:[],media:null,missing:{depth:'not-supported',internalGeometry:'not-observed',calibratedHeadPose:'not-captured'},interpretation:'observed-visible-motion-not-anatomical-limits'}
  try{const tracks=[...videoStream.getVideoTracks(),...(audioStream?.getAudioTracks()??videoStream.getAudioTracks())].filter(t=>t.readyState==='live');const stream=new MediaStream([...new Set(tracks)]);const mimeType=['video/webm;codecs=vp8,opus','video/webm','video/mp4'].find(type=>MediaRecorder.isTypeSupported(type));const capture=new MediaRecorder(stream,mimeType?{mimeType}:undefined);const chunks:BlobPart[]=[];capture.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};capture.onstop=()=>{const blob=new Blob(chunks,{type:capture.mimeType});setMedia(blob);setMediaUrl(URL.createObjectURL(blob));recorder.current=null};capture.onerror=()=>{setError('Media recording failed. Any captured motion observations are retained.');finish(true)};next.media={filename:`motion-${id}.${capture.mimeType.includes('mp4')?'mp4':'webm'}`,mimeType:capture.mimeType||mimeType||'application/octet-stream',startedAtMs:performance.now()-now,syncUncertaintyMs:null};capture.start(250);recorder.current=capture}catch(e){setError(`Could not start media recording: ${String(e)}`);return}
  draft.current=next;setActive(true)
 }
 const mark=(type:MotionMarker['type'],note:string)=>{const current=draft.current;if(!current)return;const t=performance.now()-current.timebase.originMs,p=phaseAt(t);current.markers.push({captureMs:t,repetition:p.repetition,phase:p.phase,type,source:'user',note});setCount(current.samples.length)}
 const selected=record?.samples[index],p=phaseAt(elapsed)
 const seek=(i:number)=>{setIndex(i);const ms=record?.samples[i]?.captureMs;if(player.current&&ms!==undefined)player.current.currentTime=Math.max(0,(ms-(record?.media?.startedAtMs??0))/1000)}
 const exportCapture=()=>{if(!record)return;const checked=validateLearningRecord(record);if(!checked.valid){setError(checked.errors.join('; '));return}save(new Blob([JSON.stringify(record,null,2)],{type:'application/json'}),`motion-${record.id}.json`);if(media&&record.media)save(media,record.media.filename)}
 return <section className="motion-capture"><h3>Visible motion · neutral → gesture → return</h3><p>Record three comfortable repetitions (21 seconds). Keep your head comfortable and still. Stop for discomfort. This records camera and available microphone only when you press Start.</p><div className="motion-controls"><label>Gesture <select disabled={active} value={gesture} onChange={e=>setGesture(e.target.value)}><option>Comfortable ah, then relax</option><option>Easy ee to oo, then relax</option><option>Comfortably expose tongue, then return</option></select></label><label>Context <input disabled={active} value={context} onChange={e=>setContext(e.target.value)} /></label><button disabled={active} onClick={start}>Start 3 repetitions</button><button disabled={!active} onClick={()=>finish(true)}>Stop capture</button><label>Replay JSON <input disabled={active} type="file" accept="application/json,.json" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;try{const loaded:unknown=JSON.parse(await file.text());const checked=validateLearningRecord(loaded);if(!checked.valid||!loaded||typeof loaded!=='object'||!('kind' in loaded)||loaded.kind!=='motion-observation')throw new Error(checked.errors.join('; ')||'Choose a motion-observation export');setRecord(loaded as MotionObservation);setIndex(0);setMedia(null);setMediaUrl('');setError('')}catch(err){setError(String(err))}e.target.value=''}}/></label><label>Replay companion video <input disabled={active} type="file" accept="video/*" onChange={e=>{const file=e.target.files?.[0];if(file){setMedia(file);setMediaUrl(URL.createObjectURL(file))}}}/></label></div>{error&&<p role="alert">{error}</p>}
 {active&&<div aria-live="polite"><strong>Repetition {p.repetition}/3 · {p.phase.toUpperCase()} · {(elapsed/1000).toFixed(1)}s</strong><p>{p.phase==='gesture'?gesture:p.phase==='return'?'Return comfortably to neutral':'Rest at neutral'}</p><span>{count} measured frames</span><div className="motion-controls"><button onClick={()=>mark('observed-onset','Learner marked gesture onset')}>Mark actual onset</button><button onClick={()=>mark('observed-return','Learner marked return')}>Mark actual return</button><button onClick={()=>mark('unsuccessful','Learner reports unsuccessful attempt')}>Mark unsuccessful</button></div><small>Markers are your observations; timed prompts do not prove the movement happened.</small></div>}
 {record&&<div><button onClick={exportCapture}>Export motion JSON + video</button><p>{record.samples.length} frames · {record.markers.filter(m=>m.type==='unsuccessful').length} reported unsuccessful attempts · {record.samples.filter(s=>s.gapBefore).length} timing gaps. Export before leaving this page.</p>{mediaUrl&&<video ref={player} src={mediaUrl} controls playsInline onTimeUpdate={e=>{const t=e.currentTarget.currentTime*1000+(record.media?.startedAtMs??0);let i=record.samples.findIndex(s=>s.captureMs>=t);if(i<0)i=record.samples.length-1;if(i>=0)setIndex(i)}}/>}{record.samples.length>0&&<><label>Replay measured frame <input type="range" min="0" max={record.samples.length-1} value={index} onChange={e=>seek(Number(e.target.value))}/></label><p>{selected?.captureMs.toFixed(0)}ms · repetition {selected?.repetition} · {selected?.phase}{selected?.gapBefore?' · GAP BEFORE FRAME':''}</p><svg viewBox="-1 -1 2 2" role="img" aria-label="Head-relative visible landmark replay"><path d="M -1 0 H 1 M 0 -1 V 1" stroke="#425364" strokeWidth=".01"/>{selected?.points.filter(point=>point.headRelative).map(point=><g key={point.name}><circle cx={point.headRelative![0]} cy={point.headRelative![1]} r=".025" fill={point.name==='tongue_tip'?'#fb92ba':'#70e5d0'}/><text x={point.headRelative![0]+.03} y={point.headRelative![1]} fontSize=".055" fill="white">{point.name}</text></g>)}</svg><p>{selected?.points.map(point=>`${point.name}: ${point.reason??point.visibility}`).join(' · ')}</p></>}<details><summary>Timing and visibility markers</summary><ul>{record.markers.map((m,i)=><li key={i}>{(m.captureMs/1000).toFixed(2)}s · repeat {m.repetition} · {m.type} · {m.note} ({m.source})</li>)}</ul></details></div>}
 <small>Eye-relative 2D coordinates remove approximate image translation, scale and roll. Yaw, perspective and reference movement can remain. These are uncalibrated visible estimates, not millimeters, internal muscle motion or anatomical limits. Media alignment uncertainty is unknown; this export cannot enter calibrated depth fitting.</small></section>
}
