import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,readFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {Readable} from 'node:stream';
import {createAstraRoutes} from './astra.mjs';

async function setup(t,{decide,callBudget=6}={}){
 const root=await mkdtemp(join(tmpdir(),'astra-routes-'));t.after(()=>rm(root,{recursive:true,force:true}));
 const originalEnv={url:process.env.SCIENCE_URL,token:process.env.SCIENCE_TOKEN};process.env.SCIENCE_URL='http://127.0.0.1:8766';process.env.SCIENCE_TOKEN='private';t.after(()=>{for(const [key,value] of [['SCIENCE_URL',originalEnv.url],['SCIENCE_TOKEN',originalEnv.token]]){if(value===undefined)delete process.env[key];else process.env[key]=value;}});
 const directory=join(root,'science-runs','run-one');await mkdir(directory,{recursive:true});await writeFile(join(root,'science-current.json'),JSON.stringify({status:'succeeded',runId:'run-one'}));
 const forecast={design_id:'initial',model_id:'model-one',target_observation_id:'target',rankings:[{experiment:{experiment_id:'a',pose:'a'},predictions:[{features:{brightness:3}}],status:'insufficient_distinct_hypotheses'}],feature_scales:{},minimum_separation:.05,retention_margin:.05,maximum_discrepancy:2,profile:{sample_rate_hz:44100}};
 await writeFile(join(directory,'summary.json'),JSON.stringify({sessionId:'session-one',forecast,source:'development-fixture',eligibleWindows:1,calibrationWindows:1}));
 let state={version:2,snapshot:{model_id:'model-one',hypotheses:[{hypothesis_id:'one',anatomy:{}}],evidence_ids:['voice']},pending:null,designs:{initial:{status:'unsupported',data:forecast}},attempts:[],sensations:[],jobs:[]},calls=0;const commands=[];
 const provider={getProviderStatus:()=>({available:true,configured:true,provider:'api',model:'gpt-6-astra'}),generateDecision:async args=>{calls++;return {decision:decide?await decide(args,state):{action:'record',experimentId:'a',cue:'Sing a comfortable ah.',explanation:'Compare the predicted vowel response.'},provider:'api',model:'gpt-6-astra',usage:{inputTokens:12}};}};
 const fetchImpl=async(url,options)=>{const path=new URL(url).pathname;if(path.endsWith('/state'))return Response.json({state});if(path.endsWith('/commands')){const c=JSON.parse(options.body);commands.push(c);assert.equal(c.expected_version,state.version);state.version++;if(c.action==='select_experiment'){state.designs[c.source_design_id].status='superseded';state.designs[c.design_id]={status:'committed',data:{...forecast,model_id:state.snapshot.model_id,design_id:c.design_id,target_observation_id:c.target_observation_id,selected_experiment_id:c.experiment_id}};}else if(c.action==='propose_design'){state.pending={job_id:'job-new'};}else if(c.action==='collect_job'){const proposed=commands.findLast(v=>v.action==='propose_design').parameters;state.pending=null;state.designs[proposed.design_id]={status:'unsupported',data:{...forecast,model_id:state.snapshot.model_id,design_id:proposed.design_id}};}return Response.json({state});}if(path==='/jobs/job-new')return Response.json({status:'succeeded'});throw Error(path);};
 let response;const route=createAstraRoutes({dataRoot:root,json:(_res,status,data)=>{response={status,data};},provider,fetchImpl,callBudget});
 async function request(payload,path='/api/astra/decide',headers={}){const req=Readable.from(payload===undefined?[]:[JSON.stringify(payload)]);req.method=payload===undefined?'GET':'POST';req.socket={remoteAddress:'127.0.0.1'};req.headers={host:'localhost:3000',...headers};await route(req,{},new URL(path,'http://localhost:3000'));return response;}
 return {request,root,directory,commands,state,calls:()=>calls};
}

test('decision commits actual forecast selection, preserves original summary, and replays without billing',async t=>{const s=await setup(t);const before=await readFile(join(s.directory,'summary.json'),'utf8');const a=await s.request({requestId:'one'});assert.equal(a.status,200);assert.equal(a.data.designId,'astra-design-one');assert.equal(s.commands[0].action,'select_experiment');const pointer=JSON.parse(await readFile(join(s.directory,'astra-current.json'),'utf8'));assert.equal(pointer.forecast.selected_experiment_id,'a');assert.equal(pointer.modelId,'model-one');assert.equal(await readFile(join(s.directory,'summary.json'),'utf8'),before);assert.deepEqual(await s.request({requestId:'one'}),a);assert.equal(s.calls(),1);assert.equal((await s.request({requestId:'one',goal:'different'})).status,409);});
test('updated model generates a fresh forecast before asking for and committing the next decision',async t=>{const s=await setup(t);s.state.snapshot.model_id='model-two';s.state.designs.initial.status='completed';assert.equal((await s.request({requestId:'second'})).status,200);assert.deepEqual(s.commands.map(c=>c.action),['propose_design','collect_job','select_experiment']);assert.equal(s.commands[0].parameters.max_synthesis_calls,1);});
test('unsupported actions consume bounded attempt budget without committing a capture',async t=>{const s=await setup(t,{callBudget:1,decide:()=>({action:'record',experimentId:'unknown',cue:'bad',explanation:'bad'})});assert.equal((await s.request({requestId:'bad'})).status,502);assert.equal(s.commands.length,0);assert.equal((await s.request({requestId:'bad'})).status,409);assert.equal((await s.request({requestId:'new'})).status,429);assert.equal(s.calls(),1);});
test('rest and concurrent state changes never publish a new capture design',async t=>{const s=await setup(t,{decide:()=>({action:'rest',experimentId:null,cue:'Rest your voice.',explanation:'Stop for discomfort.'})});assert.equal((await s.request({requestId:'rest'})).data.designId,null);assert.equal(s.commands.length,0);await assert.rejects(readFile(join(s.directory,'astra-current.json')));const status=await s.request(undefined,'/api/astra/status');assert.equal(status.data.remainingCalls,5);assert.equal(status.data.latest.decision.action,'rest');});
test('stale session and foreign origin reject writes',async t=>{const s=await setup(t,{decide:(_args,state)=>{state.version++;return {action:'record',experimentId:'a',cue:'ah',explanation:'test'};}});assert.equal((await s.request({requestId:'stale'})).status,409);assert.equal(s.commands.length,0);assert.equal((await s.request({requestId:'evil'},'/api/astra/decide',{origin:'https://evil.example'})).status,403);});
test('restart after scientific selection restores publication without a second provider call',async t=>{const s=await setup(t);assert.equal((await s.request({requestId:'recover'})).status,200);const path=join(s.root,'astra-decisions','session-one','recover.json'),receipt=JSON.parse(await readFile(path,'utf8'));receipt.status='running';await writeFile(path,JSON.stringify(receipt));await rm(join(s.directory,'astra-current.json'));assert.equal((await s.request({requestId:'recover'})).status,200);assert.equal(s.calls(),1);assert.equal(JSON.parse(await readFile(join(s.directory,'astra-current.json'),'utf8')).decisionId,'recover');});
test('unfinished Astra forecast resumes under a new browser request, unrelated jobs are not collected',async t=>{const s=await setup(t);s.state.snapshot.model_id='model-two';s.state.designs.initial.status='completed';const parameters={design_id:'astra-forecast-resume',target_observation_id:'astra-target-resume'};s.commands.push({action:'propose_design',parameters});s.state.pending={job_id:'job-new',request:{operation:'design_pcm',parameters}};assert.equal((await s.request({requestId:'after-reload'})).status,200);assert.deepEqual(s.commands.map(c=>c.action),['propose_design','collect_job','select_experiment']);assert.equal(s.commands[1].command_id,'astra-resume-collect_job');assert.equal(s.commands[2].source_design_id,'astra-forecast-resume');s.state.pending={job_id:'other',request:{operation:'update_pcm',parameters:{}}};assert.equal((await s.request({requestId:'another'})).status,409);s.state.pending={job_id:'other',request:{operation:'design_pcm',parameters:{design_id:'astra-forecast-foreign',target_observation_id:'unrelated'}}};assert.equal((await s.request({requestId:'again'})).status,409);assert.equal(s.calls(),1);});
