import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {Readable} from 'node:stream';
import {createHash} from 'node:crypto';
import {fileURLToPath} from 'node:url';
import {createPhonationRoutes,readPhonationContext} from './phonation.mjs';
async function setup(t,options={}){const root=await mkdtemp(join(tmpdir(),'phonation-'));t.after(()=>rm(root,{recursive:true,force:true}));await mkdir(join(root,'science-runs','run-one'),{recursive:true});await mkdir(join(root,'src/phonation'),{recursive:true});await mkdir(join(root,'server'));await writeFile(join(root,'server/phonation-worker.mjs'),'');await writeFile(join(root,'src/phonation/measure.ts'),'');await writeFile(join(root,'science-current.json'),JSON.stringify({status:'succeeded',runId:'run-one'}));await writeFile(join(root,'science-runs/run-one/summary.json'),JSON.stringify({sessionId:'session-one',createdAt:new Date().toISOString(),sourceImportSha256:'abc'}));let response,calls=0;const route=createPhonationRoutes({repo:root,dataRoot:root,enabled:true,json:(_res,status,data)=>response={status,data},analyze:async()=>{calls++;if(options.fail)throw Object.assign(Error('test'),{kind:'timed-out'});return {status:'available',reason:'test acoustic evidence',observations:[]};},...options});return {root,calls:()=>calls,request:async(method='POST')=>{const req=Readable.from([]);req.method=method;req.socket={remoteAddress:'127.0.0.1'};req.headers={host:'localhost'};await route(req,{},new URL('http://localhost/api/phonation/'+(method==='GET'?'status':'analyze')));return response;}};}
test('disabled optional feature never invokes extraction',async t=>{const s=await setup(t,{enabled:false});const r=await s.request();assert.equal(r.data.measurement.status,'disabled');assert.equal(s.calls(),0);});
test('successful saved measurements remain dated history rather than live closure coaching',async t=>{const s=await setup(t);const r=await s.request();assert.equal(r.data.measurement.status,'available');assert.equal(r.data.inference.status,'disabled');assert.equal(r.data.coaching.status,'unsupported');const restored=await readPhonationContext({dataRoot:s.root,enabled:true});assert.equal(restored.latest.id,r.data.latest.id);const stale=await readPhonationContext({dataRoot:s.root,enabled:true,now:Date.now()+600000});assert.equal(stale.descriptors,undefined);assert.ok(stale.latest);});
test('timeouts are retained and repeated failures open the session circuit',async t=>{const s=await setup(t,{fail:true});for(let i=0;i<2;i++)assert.equal((await s.request()).data.measurement.status,'timed-out');const third=await s.request();assert.equal(third.data.measurement.status,'disabled');assert.equal(third.data.latest.status,'timed-out');assert.equal((await s.request('GET')).data.measurement.status,'disabled');assert.equal((await s.request()).data.measurement.status,'disabled');assert.equal(s.calls(),3);});
test('missing optional module does not prevent baseline server routes',async t=>{const s=await setup(t);await rm(join(s.root,'src/phonation/measure.ts'));assert.equal((await s.request()).data.measurement.status,'unsupported');assert.equal(s.calls(),0);});
test('real isolated worker verifies PCM hashes and runs the canonical extractor',async t=>{const s=await setup(t),directory=join(s.root,'science-runs/run-one'),bytes=Buffer.alloc(4096*4);for(let i=0;i<4096;i++)bytes.writeFloatLE(.2*Math.sin(2*Math.PI*180*i/44100),i*4);const hash=data=>createHash('sha256').update(data).digest('hex'),artifact={id:'audio',uri:'segment-0.pcm.f32',byteLength:bytes.length,sha256:hash(bytes)};const imported=Buffer.from(JSON.stringify({declared_evidence_kind:'development-fixture',segments:[{derived_artifact:artifact,segment_id:'segment-one',sample_rate_hz:44100,source_artifacts:[{sha256:hash(bytes)}],source_clock_id:'clock-one',capture_sync_uncertainty_ms:null}]}));await mkdir(join(directory,'import'));await writeFile(join(directory,'import',artifact.uri),bytes);await writeFile(join(directory,'import/native-pcm.json'),imported);await writeFile(join(directory,'summary.json'),JSON.stringify({sessionId:'session-one',createdAt:new Date().toISOString(),sourceImportSha256:hash(imported)}));let response;const route=createPhonationRoutes({repo:fileURLToPath(new URL('..',import.meta.url)),dataRoot:s.root,enabled:true,json:(_res,status,data)=>response={status,data}});async function analyze(){const req=Readable.from([]);req.method='POST';req.socket={remoteAddress:'127.0.0.1'};req.headers={host:'localhost'};await route(req,{},new URL('http://localhost/api/phonation/analyze'));return response;}const first=await analyze();assert.equal(first.data.measurement.status,'available');assert.equal(first.data.latest.result.observations[0].schemaVersion,'phonation-observation-1.0.0');assert.equal(first.data.latest.result.observations[0].sourceKind,'development-fixture');await writeFile(join(directory,'import',artifact.uri),Buffer.alloc(bytes.length));assert.equal((await analyze()).data.measurement.status,'failed');});
