import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,rm} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {readSourceInferenceContext} from './sourceInference.mjs';

async function fixture(t){const root=await mkdtemp(join(tmpdir(),'source-state-'));t.after(()=>rm(root,{recursive:true,force:true}));const dir=join(root,'science-runs/run-one');await mkdir(dir,{recursive:true});await writeFile(join(root,'science-current.json'),JSON.stringify({status:'succeeded',runId:'run-one'}));await writeFile(join(dir,'summary.json'),JSON.stringify({sessionId:'session-one'}));await writeFile(join(dir,'source-forecast.json'),JSON.stringify({status:'succeeded',result:{baselineModelId:'model-one',forecast:{target_id:'target',status:'available'},sha256:'hash'}}));return {root,dir};}
test('disabled source capability hides prior active results without deleting history',async t=>{const {root}=await fixture(t);const state=await readSourceInferenceContext({dataRoot:root,enabled:false});assert.equal(state.forecast.status,'disabled');assert.equal(state.forecast.result,undefined);});
test('a consumed or replaced forecast is not current even when its process succeeded',async t=>{const {root}=await fixture(t),previous=globalThis.fetch,url=process.env.SCIENCE_URL,token=process.env.SCIENCE_TOKEN;process.env.SCIENCE_URL='http://127.0.0.1:8766';process.env.SCIENCE_TOKEN='test';let status='committed';globalThis.fetch=async()=>Response.json({state:{snapshot:{model_id:'model-one'},source_model:{model_id:'source-one'},source_forecasts:{target:{status,source_model_id:'source-one',baseline_model_id:'model-one'}},source_receipts:[]}});t.after(()=>{globalThis.fetch=previous;if(url===undefined)delete process.env.SCIENCE_URL;else process.env.SCIENCE_URL=url;if(token===undefined)delete process.env.SCIENCE_TOKEN;else process.env.SCIENCE_TOKEN=token;});assert.equal((await readSourceInferenceContext({dataRoot:root,enabled:true})).forecast.current,true);status='scored';assert.equal((await readSourceInferenceContext({dataRoot:root,enabled:true})).forecast.current,false);status='stale';assert.equal((await readSourceInferenceContext({dataRoot:root,enabled:true})).forecast.authoritativeStatus,'stale');});
