"""Cue-execution PCM banks through the real native engine and canonical extractor.

Observed frames are generated by the native engine (synthetic evidence). These
tests verify matching, freezing and scoring rules, not human cue execution.
"""
from copy import deepcopy
from datetime import datetime, timedelta, timezone
import hashlib

import numpy as np
import pytest

from singing_physics.control_pcm import (MIN_ATTEMPTS, SCALES, execution_support, forecast_control_pcm,
                                         residual_calibration, score_control_pcm, seal)
from singing_physics.engine import Engine
from singing_physics.pcm_design import _hash, freeze_pcm_hypotheses

WORDING = 'Sing an easy, comfortable ah and let the jaw drop.'
CONTEXT = {'capture_context_id': 'native-usb-pcm', 'source_kind': 'engine-generated', 'pitch_hz': 180.,
           'vowel': 'a', 'level': 'comfortable', 'posture': 'not-instructed'}
CONTROLS = [{'control_id': 'closed', 'JA': -2., 'f0_hz': 180.}, {'control_id': 'open', 'JA': -4.5, 'f0_hz': 180.},
            {'control_id': 'higher', 'JA': -3., 'f0_hz': 200.}]
GAIN = .8
FIRST = {'hard_palate_length': 4.2, 'pharynx_length': 7.}  # overrides; hashes use the applied anatomy
SECOND = {'hard_palate_length': 4.8, 'pharynx_length': 6.2}


def now(): return datetime.now(timezone.utc).isoformat()


def cue(wording=WORDING):
    return {'cue_id': 'astra-delivered-cue', 'cue_version': '1', 'wording': wording,
            'wording_sha256': hashlib.sha256(wording.encode()).hexdigest(), 'mode': 'elicited'}


def freeze(anatomies=(FIRST, SECOND), model_id='control-model'):
    with Engine() as engine:
        provenance = engine.provenance
    return freeze_pcm_hypotheses(model_id=model_id, evidence_ids=['calibration'], evidence_hashes=['a' * 64],
        provenance=provenance, frozen_at=now(),
        hypotheses=[{'hypothesis_id': f'h{i}', 'anatomy': anatomy} for i, anatomy in enumerate(anatomies)])


def forecast(snapshot, target, history, **changes):
    options = dict(expected_digest=snapshot.sha256, cue=cue(), context=CONTEXT, controls=CONTROLS, gain=GAIN,
                   target_id=target, history=history)
    options.update(changes)
    return forecast_control_pcm(snapshot, **options)


def frame(anatomy, control, seed):
    with Engine() as engine:
        engine.set_anatomy(anatomy)
        audio = engine.synthesize('a', {'JA': control['JA']}, f0_hz=control['f0_hz'], duration_s=.25)[4410:8506] * GAIN
    return (audio + np.random.default_rng(seed).normal(0, 1e-4, audio.shape)).tolist()


def metadata(target, index, evidence_at=None):
    return {'observationId': target, 'attemptId': f'attempt-{index}', 'artifactId': f'artifact-{index}', 'clockId': 'clock',
            'sourceKind': 'engine-generated', 'evidenceAt': evidence_at or now(),
            'sourceHashes': [hashlib.sha256(f'original-{index}'.encode()).hexdigest()]}


def weights(frozen, anatomy):
    return frozen['artifact']['execution_support']['by_anatomy'][anatomy]


@pytest.fixture(scope='module')
def learning():
    snapshot, history, forecasts = freeze(), [], []
    for index in range(MIN_ATTEMPTS + 1):
        frozen = forecast(snapshot, f'target-{index}', list(history))
        forecasts.append(frozen)
        if index < MIN_ATTEMPTS:
            history.append(score_control_pcm(frozen=frozen, pcm=frame(FIRST, CONTROLS[1], index),
                                             metadata=metadata(f'target-{index}', index)))
    return {'snapshot': snapshot, 'history': history, 'forecasts': forecasts,
            'anatomies': [_hash(h['anatomy']) for h in snapshot.data['hypotheses']]}


def test_three_matched_attempts_change_the_next_frozen_prediction(learning):
    first, second = learning['anatomies']
    ids = [c['control_id'] for c in CONTROLS]
    for index, frozen in enumerate(learning['forecasts'][:MIN_ATTEMPTS]):
        for anatomy in (first, second):
            row = weights(frozen, anatomy)
            assert row['status'] == 'uniform_insufficient_matches' and row['matched_attempts'] == index
            assert row['weights'] == {c: 1 / 3 for c in ids}
    learned = learning['forecasts'][-1]['artifact']
    assert learned['execution_support']['status'] == 'empirical'
    for anatomy in (first, second):
        row = weights(learning['forecasts'][-1], anatomy)
        support = [r['artifact']['control_support'][anatomy] for r in learning['history']]
        assert row['matched_attempts'] == 3 and row['training_score_sha256'] == [r['sha256'] for r in learning['history']]
        assert row['weights'] == {c: (1 / 3 + sum(s[c] for s in support)) / 4 for c in ids}
        assert abs(sum(row['weights'].values()) - 1) < 1e-12
    # The frames were produced with the first anatomy at the open jaw alternative.
    assert weights(learning['forecasts'][-1], first)['leading_control_ids'] == ['open']
    assert weights(learning['forecasts'][-1], first)['weights']['open'] > .4 > max(weights(learning['forecasts'][-1], first)['weights'][c] for c in ('closed', 'higher'))
    before = {p['anatomy_sha256']: p['features'] for p in learning['forecasts'][-2]['artifact']['conditional_predictions']}
    after = {p['anatomy_sha256']: p['features'] for p in learned['conditional_predictions']}
    assert before[first] != after[first] and abs(after[first]['centroidHz'] - before[first]['centroidHz']) > 1
    for prediction in learned['conditional_predictions']:
        rows = [r for r in learned['alternatives'] if r['anatomy_sha256'] == prediction['anatomy_sha256']]
        for name in SCALES:
            assert prediction['features'][name] == pytest.approx(sum(r['weight'] * r['features'][name] for r in rows), abs=1e-9)
    assert learned['model_updated'] is False and learned['movement_measured'] is False


def test_residual_calibration_is_reported_separately_and_never_applied(learning):
    first, _ = learning['anatomies']
    for index, frozen in enumerate(learning['forecasts']):
        block = frozen['artifact']['empirical_residual_calibration']
        assert block['applied_to_weights'] is False and block['applied_to_predictions'] is False
        assert block['by_anatomy'][first]['count'] == index
        assert block['by_anatomy'][first]['status'] == ('empirical' if index >= MIN_ATTEMPTS else 'insufficient')
    block = learning['forecasts'][-1]['artifact']['empirical_residual_calibration']['by_anatomy'][first]
    residuals = [next(row['residual'] for row in r['artifact']['residual_summary']['by_anatomy'] if row['anatomy_sha256'] == first)
                 for r in learning['history']]
    for name in SCALES:
        assert block['features'][name]['mean'] == pytest.approx(np.mean([r[name] for r in residuals]))
        assert block['features'][name]['sd'] == pytest.approx(np.std([r[name] for r in residuals], ddof=1))
    # The weights depend on control support only: the same computation without
    # any residual input reproduces them exactly.
    key = learning['forecasts'][-1]['artifact']['compatibility_sha256']
    recomputed = execution_support(learning['history'], key, learning['anatomies'], [c['control_id'] for c in CONTROLS])
    assert recomputed['by_anatomy'] == learning['forecasts'][-1]['artifact']['execution_support']['by_anatomy']
    assert residual_calibration(learning['history'][:2], key, learning['anatomies'], SCALES)['by_anatomy'][first]['status'] == 'insufficient'


def test_pruned_hypothesis_set_keeps_per_anatomy_history(learning):
    first, second = learning['anatomies']
    pruned = freeze([FIRST], model_id='successor-model-after-pruning')
    frozen = forecast(pruned, 'target-pruned', learning['history'])['artifact']
    original = learning['forecasts'][-1]['artifact']
    assert frozen['model_id'] != original['model_id']
    assert frozen['compatibility_sha256'] == original['compatibility_sha256']
    assert list(frozen['execution_support']['by_anatomy']) == [first]
    assert frozen['execution_support']['by_anatomy'][first] == original['execution_support']['by_anatomy'][first]
    assert second not in frozen['empirical_residual_calibration']['by_anatomy']


@pytest.mark.parametrize('change', [
    {'cue': cue('Sing an easy, comfortable ah.')},
    {'context': {**CONTEXT, 'level': 'soft'}},
    {'context': {**CONTEXT, 'capture_context_id': 'laptop-microphone'}},
    {'controls': [CONTROLS[0], CONTROLS[1], {**CONTROLS[2], 'f0_hz': 210.}]},
    {'gain': 1.6},
    {'feature_scales': {**SCALES, 'pitchHz': {**SCALES['pitchHz'], 'scale': 10.}}},
    {'profile': {'sample_rate_hz': 48000, 'frame_start_sample': 4800, 'frame_size': 4096, 'duration_s': .25}},
], ids=['wording', 'level', 'capture-context', 'bank', 'gain', 'scales', 'profile'])
def test_changed_binding_or_runtime_excludes_history(learning, change):
    snapshot = freeze([FIRST])
    frozen = forecast(snapshot, 'target-changed', learning['history'], **change)['artifact']
    support = frozen['execution_support']
    assert support['status'] == 'uniform_insufficient_matches' and support['eligible_attempts'] == 0
    assert [row['attempt_id'] for row in support['excluded']] == ['attempt-0', 'attempt-1', 'attempt-2']
    assert all(row['reason'].startswith('incompatible') for row in support['excluded'])
    assert set(frozen['compatibility']) == {'native', 'extractor', 'profile', 'feature_scales', 'cue', 'context', 'controls', 'gain', 'policy'}


def test_repeated_physical_evidence_in_history_is_rejected(learning):
    snapshot, history = learning['snapshot'], learning['history']
    with pytest.raises(ValueError, match='repeated physical evidence'):
        forecast(snapshot, 'target-duplicate', [history[0], history[0]])
    alias = deepcopy(history[1]['artifact']); alias['attempt_id'] = history[0]['artifact']['attempt_id']
    with pytest.raises(ValueError, match='repeated physical evidence'):
        forecast(snapshot, 'target-duplicate', [history[0], seal(alias)])
    tampered = deepcopy(history[0]); tampered['artifact']['control_support'] = {}
    with pytest.raises(ValueError, match='integrity'):
        forecast(snapshot, 'target-duplicate', [tampered])
    with pytest.raises(ValueError, match='aliases'):
        forecast(snapshot, history[0]['artifact']['target_id'], history)


def test_outcome_must_follow_seal_and_bring_new_evidence(learning):
    frozen = learning['forecasts'][-1]
    sealed = datetime.fromisoformat(frozen['artifact']['sealed_at'])
    pcm = frame(FIRST, CONTROLS[0], 99)
    with pytest.raises(ValueError, match='follow forecast commitment'):
        score_control_pcm(frozen=frozen, pcm=pcm, metadata=metadata('target-3', 3, (sealed - timedelta(seconds=1)).isoformat()))
    with pytest.raises(ValueError, match='prospective target'):
        score_control_pcm(frozen=frozen, pcm=pcm, metadata=metadata('target-2', 3))
    with pytest.raises(ValueError, match='reuses previous physical evidence'):
        score_control_pcm(frozen=frozen, pcm=pcm, metadata=metadata('target-3', 0))
    with pytest.raises(ValueError, match='evidence kind'):
        score_control_pcm(frozen=frozen, pcm=pcm, metadata={**metadata('target-3', 3), 'sourceKind': 'human-observation'})


def test_gain_is_a_bank_nuisance_outside_execution_support(learning):
    with pytest.raises(ValueError, match='gain is a bank-wide nuisance'):
        forecast(learning['snapshot'], 'target-gain', [], controls=[{**c, 'gain': GAIN} for c in CONTROLS])
    learned = learning['forecasts'][-1]['artifact']
    assert learned['gain'] == GAIN and learned['compatibility']['gain'] == GAIN
    assert all(set(row['controls']) == {'control_id', 'JA', 'f0_hz'} for row in learned['alternatives'])
    for receipt in learning['history']:
        for mass in receipt['artifact']['control_support'].values():
            assert set(mass) == {'closed', 'open', 'higher'}


def test_missing_features_leave_the_attempt_unscorable_and_uncounted(learning):
    frozen = learning['forecasts'][-1]
    silent = score_control_pcm(frozen=frozen, pcm=[0.] * 4096, metadata=metadata('target-3', 7))
    receipt = silent['artifact']
    assert receipt['status'] == 'unscorable' and receipt['control_support'] == {}
    assert 'missing' in receipt['reason'] and len(receipt['alternatives']) == len(frozen['artifact']['alternatives'])
    assert all(row['status'] == 'unscorable' and row['standardized_square_sum'] is None for row in receipt['alternatives'])
    key = frozen['artifact']['compatibility_sha256']
    support = execution_support(learning['history'] + [silent], key, learning['anatomies'], ['closed', 'open', 'higher'])
    assert support['eligible_attempts'] == 3
    assert support['excluded'] == [{'score_sha256': silent['sha256'], 'attempt_id': 'attempt-7', 'reason': 'no complete anatomy support: ' + receipt['reason']}]
    assert support['by_anatomy'] == frozen['artifact']['execution_support']['by_anatomy']


def test_budget_is_bounded_and_timeout_stops_remaining_alternatives(learning):
    snapshot = learning['snapshot']
    with pytest.raises(ValueError, match='integer from 1 to 96'):
        forecast(snapshot, 'target-budget', [], max_synthesis_calls=97)
    bank = [{'control_id': f'c{i}', 'JA': -1.25 - .25 * i, 'f0_hz': 180.} for i in range(16)]
    with pytest.raises(ValueError, match='cannot cover'):
        forecast(snapshot, 'target-budget', [], controls=bank, max_synthesis_calls=31)
    stopped = forecast(snapshot, 'target-timeout', [], controls=bank, max_synthesis_calls=32, timeout_s=1)['artifact']
    assert stopped['status'] == 'incomplete' and stopped['declared_synthesis_calls'] == 32
    assert stopped['actual_synthesis_calls'] < 32 and len(stopped['alternatives']) == 32
    halted = [row for row in stopped['alternatives'] if row['status'] == 'stopped']
    assert halted and all(row['features'] is None and 'timed out' in row['reason'] for row in halted)
    assert stopped['conditional_predictions'][-1] == {'hypothesis_id': 'h1', 'anatomy_sha256': learning['anatomies'][1], 'status': 'incomplete', 'features': None}


def test_job_service_runs_the_control_bank_in_its_isolated_worker(tmp_path, learning):
    from singing_physics.service import JobService
    snapshot = freeze([FIRST])
    parameters = {'snapshot_json': snapshot.content.decode(), 'expected_digest': snapshot.sha256, 'cue': cue(),
                  'context': CONTEXT, 'controls': CONTROLS, 'gain': GAIN, 'target_id': 'service-target', 'history': learning['history']}
    with JobService(tmp_path / 'jobs') as service:
        with pytest.raises(ValueError, match='Missing operation parameters'):
            service.submit({'operation': 'forecast_control_pcm', 'parameters': {k: v for k, v in parameters.items() if k != 'history'}}, idempotency_key='no-history')
        with pytest.raises(ValueError, match='does not match job model'):
            service.submit({'operation': 'forecast_control_pcm', 'parameters': parameters, 'session_id': 's', 'model_id': 'other'}, idempotency_key='wrong-model')
        job = service.submit({'operation': 'forecast_control_pcm', 'parameters': parameters}, idempotency_key='forecast')
        assert service.wait(job, 60)['status'] == 'succeeded'
        frozen = service.result(job)
        assert frozen['artifact']['execution_support']['by_anatomy'] == {
            learning['anatomies'][0]: learning['forecasts'][-1]['artifact']['execution_support']['by_anatomy'][learning['anatomies'][0]]}
        scored = service.submit({'operation': 'score_control_pcm', 'parameters': {'frozen': frozen, 'pcm': frame(FIRST, CONTROLS[0], 11),
                                 'metadata': metadata('service-target', 11)}}, idempotency_key='score')
        assert service.wait(scored, 60)['status'] == 'succeeded'
        assert service.result(scored)['artifact']['status'] == 'scored'
