"""Optional source inference through actual app routes and isolated native jobs.

All audio here is generated by the prescribed native source model. These tests
verify software lineage and graceful fallback, not vocal-fold closure or anatomy.
The test server never imports the live Astra provider or an environment file.
"""
from contextlib import contextmanager
from datetime import datetime, timezone
import hashlib
import json
import os
from pathlib import Path
import socket
import subprocess
import sys
import threading
import time
import urllib.error
import urllib.request
import zipfile

from singing_physics.engine import Engine
from singing_physics.http_service import ScientificHTTPServer
from singing_physics.phonation import synthesize_phonation
from singing_physics.pcm_inverse import resample_native_pcm
from test_live_capture_jobs import capture


BOOTSTRAP = r"""
import http from 'node:http';
import {pathToFileURL} from 'node:url';
import {resolve} from 'node:path';
const repo=process.cwd(),dataRoot=process.env.LOCAL_DATA_DIR;
const load=name=>import(pathToFileURL(resolve(repo,'server',name)));
const json=(res,status,value)=>{res.writeHead(status,{'Content-Type':'application/json'});res.end(JSON.stringify(value))};
const routes=[(await load('sourceInference.mjs')).createSourceInferenceRoutes({repo:process.env.SOURCE_TEST_RUNNER_REPO||repo,dataRoot,json,enabled:process.env.PHONATION_SOURCE_ENABLED==='1'}),
  (await load('science.mjs')).scienceRoutes({repo,dataRoot,json}),
  (await load('voiceCapture.mjs')).createVoiceCaptureRoutes({repo,dataRoot,json})];
const proxy=(await load('science-proxy.mjs')).createScienceProxy({url:process.env.SCIENCE_URL,token:process.env.SCIENCE_TOKEN});
http.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://localhost');
  for(const route of routes)if(await route(req,res,url))return;
  if(url.pathname.startsWith('/api/science/'))return proxy(req,res);
  json(res,404,{error:'No test route'});
}catch(e){json(res,500,{error:e.message})}}).listen(Number(process.env.PORT),'127.0.0.1');
"""


def generated_capture(parent, identity, *, anatomy=None, pose='a', f0=180., ps=.2,
                      ja=-3., pressure=8000., gain=1.):
    """Original artifact bytes and manifests, not fabricated acoustic descriptors."""
    directory = capture(parent)
    with Engine() as engine:
        if anatomy is not None:
            engine.set_anatomy(anatomy)
        audio, _ = synthesize_phonation(engine, pose=pose, JA=ja, F0=f0,
            PR=pressure, PS=ps, duration_s=.6)
        samples, _ = resample_native_pcm(audio, 44100, 48000)
    raw = (samples * gain).astype('<f4').tobytes()
    (directory / 'audio.pcm.raw').write_bytes(raw)
    manifest = json.loads((directory / 'manifest.json').read_text())
    manifest['capture_id'] = identity
    manifest['created_at'] = datetime.now(timezone.utc).isoformat()
    manifest['task'] = 'Explicit prescribed-source synthetic software integration fixture'
    manifest['audio']['samples'][0]['artifact'].update(
        bytes=len(raw), sha256=hashlib.sha256(raw).hexdigest())
    (directory / 'manifest.json').write_text(json.dumps(manifest))
    return directory


def publish_capture(data, directory):
    manifest = json.loads((directory / 'manifest.json').read_text())
    imports = data / 'usb-imports'
    imports.mkdir(exist_ok=True)
    archive = imports / ('capture-' + manifest['capture_id'] + '.zip')
    with zipfile.ZipFile(archive, 'w') as zipped:
        for file in directory.iterdir():
            zipped.write(file, file.name)
    (data / 'native-pull-latest.json').write_text(json.dumps({
        'name': archive.name, 'bytes': archive.stat().st_size,
        'sha256': hashlib.sha256(archive.read_bytes()).hexdigest()}))


@contextmanager
def app_runtime(tmp_path, bootstrap):
    root = Path(__file__).parents[2]
    data = tmp_path / 'app'
    data.mkdir(exist_ok=True)
    with socket.socket() as sock:
        sock.bind(('127.0.0.1', 0))
        port = sock.getsockname()[1]
    with ScientificHTTPServer(tmp_path / 'worker', 't' * 48, port=0) as worker:
        thread = threading.Thread(target=worker.serve_forever, daemon=True)
        thread.start()
        env = {**os.environ, 'PORT': str(port), 'LOCAL_DATA_DIR': str(data),
            'SINGING_PYTHON': sys.executable,
            'SCIENCE_URL': f'http://127.0.0.1:{worker.server_port}',
            'SCIENCE_TOKEN': 't' * 48, 'PHONATION_SOURCE_ENABLED': '1'}
        env.pop('OPENAI_API_KEY', None)
        env.pop('SINGING_TEST_LIVE_ASTRA_ENV', None)
        process = None
        log = (tmp_path / 'app.log').open('w')

        def call(path, body=None, expected=200):
            request = urllib.request.Request(f'http://127.0.0.1:{port}' + path,
                method='GET' if body is None else 'POST',
                data=None if body is None or body is False else json.dumps(body).encode(),
                headers={'Content-Type': 'application/json'})
            try:
                response = urllib.request.urlopen(request, timeout=180)
            except urllib.error.HTTPError as error:
                response = error
            with response:
                result = json.load(response)
                assert response.status == expected, (path, response.status, result)
                return result

        def stop():
            if process is not None:
                process.terminate()
                try:
                    process.wait(timeout=5)
                except subprocess.TimeoutExpired:
                    process.kill()
                    process.wait()

        def restart(enabled=True, source_repo=None):
            nonlocal process
            stop()
            env['PHONATION_SOURCE_ENABLED'] = '1' if enabled else '0'
            if source_repo is None:
                env.pop('SOURCE_TEST_RUNNER_REPO', None)
            else:
                env['SOURCE_TEST_RUNNER_REPO'] = str(source_repo)
            process = subprocess.Popen(['node', '--input-type=module', '-e', bootstrap],
                cwd=root, env=env, stdout=log, stderr=log)
            for _ in range(100):
                try:
                    call('/api/science/health')
                    return
                except OSError:
                    assert process.poll() is None, (tmp_path / 'app.log').read_text()
                    time.sleep(.1)
            raise AssertionError('Application did not start')

        try:
            restart()
            yield data, call, restart
        finally:
            stop()
            log.close()
            worker.shutdown()
            thread.join()


def wait_for(call, path, *, terminal=('succeeded',), timeout=180):
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        state = call(path)
        if state['status'] != 'running':
            assert state['status'] in terminal, state
            return state
        time.sleep(.1)
    raise AssertionError(f'{path} did not complete')


def wait_source(call, kind, *, timeout=180, terminal='succeeded'):
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        state = call('/api/source/status')
        if not state['running']:
            assert state[kind]['status'] == terminal, state
            return state[kind].get('result')
        time.sleep(.1)
    raise AssertionError(f'Source {kind} did not complete')


def test_optional_source_fit_forecast_later_capture_score_and_restart(tmp_path):
    with app_runtime(tmp_path, BOOTSTRAP) as (data, call, restart):
        empty = call('/api/source/status')
        assert empty['fit']['status'] == 'unsupported'
        original = generated_capture(data, '00000000-0000-4000-8000-000000000010')
        publish_capture(data, original)
        assert call('/api/science/use-latest-capture', {
            'purpose': 'calibration', 'pose': 'a', 'contains_external_excitation': False})['prepared']
        started = call('/api/science/run', False, expected=202)
        fitted = wait_for(call, '/api/science/status')['result']
        run = data / 'science-runs' / started['runId']
        summary_bytes = (run / 'summary.json').read_bytes()
        session_path = '/api/science/sessions/' + fitted['sessionId'] + '/state'
        baseline = call(session_path)['state']['snapshot']

        call('/api/source/analyze', False, expected=202)
        deadline = time.monotonic() + 15
        while time.monotonic() < deadline:
            pending = call(session_path)['state'].get('pending')
            if pending is not None:
                assert pending['request']['operation'] == 'fit_phonation'
                break
            time.sleep(.02)
        else:
            raise AssertionError('Source worker never acquired its session job')
        # Interrupt the app-owned observer while the isolated native job exists.
        # The explicit retry must recover that same scientific job identity.
        interrupted_job = pending['job_id']
        restart()
        assert call(session_path)['state']['snapshot'] == baseline
        call('/api/source/analyze', False, expected=202)
        wait_source(call, 'fit')
        enhanced = call(session_path)['state']
        assert sum(job['job_id'] == interrupted_job for job in enhanced['jobs']) == 1
        assert sum(job['request']['operation'] == 'fit_phonation' for job in enhanced['jobs']) == 1
        assert enhanced['snapshot'] == baseline
        model = enhanced['source_model']
        assert model is not None
        assert model['baseline_model_id'] == baseline['model_id']
        assert model['closure_contact_inference'] is False
        assert model['result']['status'] == 'available'
        assert (run / 'summary.json').read_bytes() == summary_bytes

        # Both disabled and restarted apps preserve the independent valid model.
        restart(enabled=False)
        assert call('/api/source/status')['enabled'] is False
        call('/api/source/analyze', False)
        assert call(session_path)['state']['source_model'] == model
        assert call(session_path)['state']['snapshot'] == baseline
        restart()
        assert call('/api/source/status')['fit']['status'] == 'succeeded'
        before_retry = call(session_path)['state']['version']
        call('/api/source/analyze', False)
        assert call(session_path)['state']['version'] == before_retry

        call('/api/source/forecast', False, expected=202)
        wait_source(call, 'forecast')
        predicted = call(session_path)['state']
        target, committed = next(iter(predicted['source_forecasts'].items()))
        assert committed['status'] == 'committed'
        assert committed['source_model_id'] == model['model_id']
        assert committed['baseline_model_id'] == baseline['model_id']
        frozen = committed['artifact']['forecast']
        assert frozen['target_id'] == target
        assert frozen['status'] == 'available'
        restart()
        call('/api/source/forecast', False)
        assert call(session_path)['state']['version'] == predicted['version']

        later_root = data / 'later'
        later_root.mkdir()
        controls = frozen['controls']
        later = generated_capture(later_root, '00000000-0000-4000-8000-000000000011',
            anatomy=frozen['anatomy'], f0=controls['F0'], ps=controls['PS'],
            ja=controls['JA'], pressure=controls['PR'], gain=controls['gain'])
        publish_capture(data, later)
        call('/api/source/score', False, expected=202)
        result = wait_source(call, 'score')
        scored = call(session_path)['state']
        assert scored['snapshot'] == baseline
        assert scored['source_model']['model_id'] == model['model_id']
        recorded = scored['source_forecasts'][target]
        assert recorded['status'] == 'scored', result
        assert recorded['score_result']['status'] == 'available'
        assert recorded['score_result']['model_updated'] is False
        assert recorded['score_result']['score'] is not None
        assert (run / 'summary.json').read_bytes() == summary_bytes
        restart()
        call('/api/source/score', False)
        assert call(session_path)['state']['version'] == scored['version']

        # Simulate an optional runner omitted from an installation, while the
        # ordinary scientific routes still use the actual complete repository.
        absent = tmp_path / 'without-optional-source-runner'
        absent.mkdir()
        restart(source_repo=absent)
        call('/api/source/forecast', False, expected=202)
        wait_source(call, 'forecast', terminal='failed')
        preserved = call(session_path)['state']
        assert preserved['snapshot'] == baseline
        assert preserved['source_model'] == model
        assert preserved['version'] == scored['version']
        restart()
        call('/api/source/forecast', False, expected=202)
        wait_source(call, 'forecast')
        recovered = call(session_path)['state']
        committed_targets = [key for key, value in recovered['source_forecasts'].items()
            if value['status'] == 'committed']
        assert len(committed_targets) == 1 and committed_targets[0] != target
        assert recovered['snapshot'] == baseline
