"""Cue-execution learning through the actual app routes, Astra route and isolated native jobs.

Every recording is generated by the native engine (synthetic evidence). The
provider is a deterministic test fixture; no live model is called. This proves
software lineage and the repeated-attempt rule, not human cue execution.
"""
import time

from test_app_source_loop import app_runtime, generated_capture, publish_capture, wait_for

BOOTSTRAP = r"""
import http from 'node:http';
import {pathToFileURL} from 'node:url';
import {resolve} from 'node:path';
const repo=process.cwd(),dataRoot=process.env.LOCAL_DATA_DIR;
const load=name=>import(pathToFileURL(resolve(repo,'server',name)));
const json=(res,status,value)=>{res.writeHead(status,{'Content-Type':'application/json'});res.end(JSON.stringify(value))};
const provider={getProviderStatus:()=>({available:true,provider:'test-only'}),generateDecision:async({input,schema})=>{
  const control=input.controlLearning;
  if(!control||control.modelUpdated!==false||control.baselineModelId!==input.modelId)throw Error('Cue-execution context did not reach the provider');
  const selected=input.forecast.experiments.find(row=>row.experiment.pose==='a')||input.forecast.experiments[0];
  const decision={action:'record',experimentId:selected.experiment.experiment_id,cue:'Sing an easy, comfortable ah.',
    explanation:'Test-only decision that repeats the delivered cue so attempts can be matched.'};
  if(schema.properties.cueBindingId){
    const binding=control.bindings.find(row=>row.context.vowel===selected.experiment.pose);
    decision.cueBindingId=binding?binding.bindingId:null;
    if(binding)decision.cue='A paraphrase that the app must replace with the frozen wording.';
  }
  return {decision,provider:'test-only',model:'deterministic-test-fixture',usage:{}};
}};
const routes=[(await load('astra.mjs')).createAstraRoutes({dataRoot,json,provider}),
  (await load('controlLearning.mjs')).createControlLearningRoutes({repo,dataRoot,json}),
  (await load('sessionExport.mjs')).createSessionExportRoutes({dataRoot,json}),
  (await load('science.mjs')).scienceRoutes({repo,dataRoot,json}),
  (await load('voiceCapture.mjs')).createVoiceCaptureRoutes({repo,dataRoot,json})];
const proxy=(await load('science-proxy.mjs')).createScienceProxy({url:process.env.SCIENCE_URL,token:process.env.SCIENCE_TOKEN});
http.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://localhost');
  for(const route of routes)if(await route(req,res,url))return;
  if(url.pathname.startsWith('/api/science/'))return proxy(req,res);
  json(res,404,{error:'No test route'});
}catch(e){json(res,500,{error:e.message})}}).listen(Number(process.env.PORT),'127.0.0.1',function(){console.log('App: http://127.0.0.1:'+this.address().port)});
"""


def wait_control(call, phase, timeout=180):
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        status = call('/api/control/status')
        if not status['running']:
            assert status[phase]['status'] == 'succeeded', status[phase].get('reason')
            return status
        time.sleep(.1)
    raise AssertionError(f'Control {phase} did not complete')


def weights(forecast):
    return {sha: row['weights'] for sha, row in forecast['artifact']['artifact']['execution_support']['by_anatomy'].items()}


def test_repeated_delivered_cue_changes_the_fourth_forecast(tmp_path):
    with app_runtime(tmp_path, BOOTSTRAP) as (data, call, restart):
        assert call('/api/control/status')['status'] == 'unsupported'
        publish_capture(data, generated_capture(data, '00000000-0000-4000-8000-000000000020'))
        assert call('/api/science/use-latest-capture', {'purpose': 'calibration', 'pose': 'a', 'contains_external_excitation': False})['prepared']
        call('/api/science/run', False, expected=202)
        fitted = wait_for(call, '/api/science/status')['result']
        session_path = '/api/science/sessions/' + fitted['sessionId'] + '/state'
        baseline = call(session_path)['state']['snapshot']
        assert call('/api/control/forecast', False, expected=409)['error'].startswith('Ask Astra')
        forecasts, decisions = [], []
        for round in range(4):
            decisions.append(call('/api/astra/decide', {'requestId': f'control-round-{round}', 'goal': 'Repeat a comfortable vowel'}))
            assert decisions[-1]['status'] == 'succeeded'
            call('/api/control/forecast', False, expected=202)
            status = wait_control(call, 'forecast')
            state = call(session_path)['state']
            forecast_id = status['forecast']['result']['forecastId']
            forecasts.append(state['control_forecasts'][forecast_id])
            assert forecasts[-1]['status'] == 'committed' and status['forecast']['result']['deliveredCue'] == 'Sing an easy, comfortable ah.'
            if round == 3:
                break
            later = data / f'later-{round}'
            later.mkdir()
            # Deterministic synthesis would repeat identical bytes, which the ledger rejects as
            # reused evidence; a small level change makes each attempt a distinct recording.
            publish_capture(data, generated_capture(later, f'00000000-0000-4000-8000-00000000003{round}',
                anatomy=baseline['hypotheses'][0]['anatomy'], ja=-4., gain=1. + .02 * round))
            call('/api/control/score', False, expected=202)
            scored = wait_control(call, 'score')['score']['result']
            assert scored['status'] in ('scored', 'partial') and scored['modelUpdated'] is False, scored
            # A retry of the same attempt returns the stored receipt instead of scoring twice.
            assert call('/api/control/score', False)['result']['jobId'] == scored['jobId']
            if round == 0:
                # The decision's prediction is used; freezing again needs a new Astra decision.
                assert 'already used' in call('/api/control/forecast', False, expected=409)['error']

        state = call(session_path)['state']
        assert state['snapshot'] == baseline
        assert len(state['control_bindings']) == 1
        assert {f['binding_id'] for f in forecasts} == set(state['control_bindings'])
        assert [d['decision'].get('cueBindingId') for d in decisions] == [None] + [forecasts[0]['binding_id']] * 3
        assert all(d['providerCue'].startswith('A paraphrase') and d['decision']['cue'] == 'Sing an easy, comfortable ah.' for d in decisions[1:])
        uniform = {c['control_id']: 1 / 5 for c in state['control_bindings'][forecasts[0]['binding_id']]['controls']}
        for index, forecast in enumerate(forecasts[:3]):
            assert all(row == uniform for row in weights(forecast).values()), index
        learned = forecasts[3]['artifact']['artifact']
        assert learned['execution_support']['status'] == 'empirical'
        assert all(row != uniform for row in weights(forecasts[3]).values())
        before = {p['anatomy_sha256']: p['features'] for p in forecasts[2]['artifact']['artifact']['conditional_predictions']}
        assert any(p['features'] != before[p['anatomy_sha256']] for p in learned['conditional_predictions'])
        assert learned['empirical_residual_calibration']['applied_to_weights'] is False

        status = call('/api/control/status')
        [binding] = status['bindings']
        assert binding['attempts']['scored'] == 3 and binding['latestForecast']['current'] is True
        assert all(row['forecastMatchedAttempts'] == 3 and row['supportStatus'] == 'empirical' for row in binding['latestForecast']['anatomies'])

        # After four forecasts and three scores the ledger replay still fits the exporter's bound,
        # so every lane's receipts stay bound (control jobs keep digests, not payload copies).
        exported = call('/api/session-export')
        assert not any(row['source'] == 'worker/session-replay' for row in exported['missing']), exported['missing']
        assert all(row['reason'] == 'Not recorded' for row in exported['missing']), exported['missing']
        assert exported['summary']['controlScoreCount'] == 3
        bound = [a['binding'] for a in exported['artifacts'] if a.get('binding', {}).get('role', '').startswith('cue-execution-')]
        assert sorted(b['role'] for b in bound) == ['cue-execution-forecast'] * 4 + ['cue-execution-score'] * 3
        assert all(b['originalBytesVerified'] and b['modelUpdated'] is False for b in bound if b['role'] == 'cue-execution-score')
