import test from 'node:test'
import assert from 'node:assert/strict'
import { mkdtemp, writeFile, rm, symlink } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { createHash } from 'node:crypto'
import { importNativeCapture } from './import-native-capture.ts'
import { validateRecord } from '../src/contracts/index.ts'
async function fixture(){const directory=await mkdtemp(join(tmpdir(),'native-kit-fixture-'));const artifact=async(path:string,data:Buffer)=>{await writeFile(join(directory,path),data);return {path,bytes:data.length,sha256:createHash('sha256').update(data).digest('hex')}};const t=(value:number)=>({value,timescale:1000,epoch:0,flags:1,seconds:value/1000});const depth=Buffer.alloc(8);depth.writeFloatLE(.35);depth.writeFloatLE(NaN,4);const frame={sequence:0,capture_clock_timestamp:t(1000),rgb_timestamp:t(1001),depth_timestamp:t(1000),rgb_dimensions:[2,1],rgb:await artifact('rgb.jpg',Buffer.from([255,216,255,217])),rgb_dropped:false,depth:await artifact('depth.depth.f32',depth),depth_dropped:false,depth_unit:'m',depth_storage:'row-major-little-endian-float32-packed',depth_dimensions:[2,1],depth_filtered:false,depth_accuracy_label:'relative',calibration:{intrinsics_row_major:[[1,0,0],[0,1,0],[0,0,1]],intrinsic_reference_dimensions:[2,1],extrinsics_3x4_row_major:[[1,0,0,0],[0,1,0,0],[0,0,1,0]],pixel_size_mm:.01,lens_distortion_center:[1,1],lens_distortion_table_base64:null,inverse_lens_distortion_table_base64:null}};const sample={presentation_timestamp:t(999),duration:t(1),num_samples:2,artifact:await artifact('audio.pcm.raw',Buffer.alloc(4)),asbd:{sample_rate:2000,format_id:1819304813,format_flags:4,bytes_per_frame:2,channels_per_frame:1}};const manifest={schema_version:'singing-native-rgbd-1.0.0',capture_mode:'one-held-pose',capture_id:'fixture',created_at:'2026-09-10T12:00:00Z',task:'software fixture only',device:{device_type:'AVCaptureDeviceTypeBuiltInTrueDepthCamera',position:'front',output_mirrored:false},frames:[frame],audio:{reason:'',samples:[sample]}};const save=()=>writeFile(join(directory,'manifest.json'),JSON.stringify(manifest));await save();return {directory,manifest,save}}
test('native source samples/PCM/calibration convert to valid KIT without invented sync or metric accuracy',async()=>{const f=await fixture();try{const result=await importNativeCapture(f.directory,'fixture-participant','fixture-session'),record=result.records[0];assert.equal(validateRecord(record).valid,true);const depth=record.streams.find(s=>s.modality==='depth')!,audio=record.streams.find(s=>s.modality==='audio')!;assert.equal(depth.samples[0].captureMs,1000);assert.equal(audio.samples[0].captureMs,999);assert.equal(depth.samples[0].quality.missingReason,'not-calibrated');assert.notEqual(depth.timebase.clockId,audio.timebase.clockId);assert.equal(depth.timebase.offsetToReferenceMs,null);assert.equal(audio.timebase.syncUncertaintyMs,null);assert.match(depth.calibration.artifactId!,/manifest.json/);assert.equal(record.artifacts.length,4)}finally{await rm(f.directory,{recursive:true,force:true})}})
test('hash mismatches, path escapes and symlinks are rejected',async()=>{const f=await fixture();try{await writeFile(join(f.directory,'audio.pcm.raw'),Buffer.from('changed'));await assert.rejects(importNativeCapture(f.directory,'p','s'),/hash or byte/);await rm(join(f.directory,'audio.pcm.raw'));await symlink('/etc/hosts',join(f.directory,'audio.pcm.raw'));await assert.rejects(importNativeCapture(f.directory,'p','s'));f.manifest.frames[0].rgb.path='../elsewhere';await f.save();await assert.rejects(importNativeCapture(f.directory,'p','s'),/Unsafe local/)}finally{await rm(f.directory,{recursive:true,force:true})}})
test('no calibration stays missing and invalid ASBD or mixed filtering fails',async()=>{const f=await fixture();try{Object.assign(f.manifest.frames[0],{calibration:null});await f.save();const record=(await importNativeCapture(f.directory,'p','s')).records[0];assert.equal(record.streams.find(s=>s.modality==='depth')!.calibration.artifactId,null);f.manifest.audio.samples[0].asbd.bytes_per_frame=4;await f.save();await assert.rejects(importNativeCapture(f.directory,'p','s'),/LPCM/);f.manifest.audio.samples[0].asbd.bytes_per_frame=2;f.manifest.frames.push({...f.manifest.frames[0],sequence:1,depth_filtered:true});await f.save();await assert.rejects(importNativeCapture(f.directory,'p','s'),/filtering/)}finally{await rm(f.directory,{recursive:true,force:true})}})
