import { useEffect, useRef, useState } from 'react'
import { CUE_LIBRARY, REVIEW_ONLY_CANDIDATES } from '../../experiment/cues/library.ts'
import type { TeachingCue, LearningProtocol, LearningAttempt, LearningArm, LearningPhase } from '../../experiment/cues/types.ts'
import { freezeLearningProtocol, evaluateLearning, compareLearning } from '../../evaluation/learning/index.ts'
import type { LearningScore } from '../../evaluation/learning/index.ts'
import { storeLearningMedia, readLearningMedia, extractLearningPitch } from '../../experiment/cues/media.ts'
import { RecordingControls } from '../recording/RecordingControls.tsx'
import type { RecordingController } from '../recording/RecordingControls.tsx'
import { exportLearningInterchange, learningInstruction } from '../../experiment/cues/interchange.ts'
import './CoachLearningPanel.css'
const KEY='singing-teacher-learning-v1'
type Saved={pendingAttempt?:LearningAttempt|null;protocol:LearningProtocol|null;protocolHistory?:LearningProtocol[];attempts:LearningAttempt[];mnemonics:Record<string,string>}
function load():Saved{try{const raw=localStorage.getItem(KEY);if(raw){const parsed=JSON.parse(raw);if(Array.isArray(parsed.attempts)&&parsed.mnemonics&&typeof parsed.mnemonics==='object'){if(parsed.pendingAttempt){const pending=parsed.pendingAttempt as LearningAttempt;if(!parsed.attempts.some((a:LearningAttempt)=>a.id===pending.id))parsed.attempts.push({...pending,endedAt:pending.endedAt||new Date().toISOString(),outcome:'failed',failureReason:'Page closed before attempt/report was finalized; incomplete attempt retained'});parsed.pendingAttempt=null}return parsed}}}catch{/* Storage may be unavailable. */}return {protocol:null,attempts:[],mnemonics:{}}}
function download(value:unknown){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='singing-learning-evidence.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
export default function CoachLearningPanel({videoStream,audioStream}:{videoStream?:MediaStream|null;audioStream?:MediaStream|null}){
 const [saved,setSaved]=useState(load),[cue,setCue]=useState<TeachingCue>(CUE_LIBRARY[0]),[reviewer,setReviewer]=useState(''),[role,setRole]=useState(''),[reviewEvidence,setReviewEvidence]=useState('')
 const [target,setTarget]=useState('220'),[tolerance,setTolerance]=useState('50'),[context,setContext]=useState('ah · comfortable level · seated'),[phrase,setPhrase]=useState('Hello again'),[delay,setDelay]=useState('24')
 const [arm,setArm]=useState<LearningArm>(()=>{try{return localStorage.getItem(KEY+'-arm')==='variant'?'variant':'baseline'}catch{return 'baseline'}}),[phase,setPhase]=useState<LearningPhase>(()=>{try{const v=localStorage.getItem(KEY+'-phase');return v==='recall'||v==='transfer'||v==='retention'?v:'prompted'}catch{return 'prompted'}}),[confirmed,setConfirmed]=useState(false),[deviations,setDeviations]=useState(''),[words,setWords]=useState(''),[region,setRegion]=useState(''),[effort,setEffort]=useState(2),[confidence,setConfidence]=useState(3),[recognizable,setRecognizable]=useState(false),[mnemonic,setMnemonic]=useState(''),[discomfort,setDiscomfort]=useState(false)
 const [active,setActive]=useState<LearningAttempt|null>(null),[draft,setDraft]=useState<LearningAttempt|null>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[scores,setScores]=useState<LearningScore[]>([]),[replay,setReplay]=useState<{url:string;filename:string}|null>(null)
 const [sessionId]=useState(()=>crypto.randomUUID());const recorder=useRef<RecordingController|null>(null)
 const protocol=saved.protocol,hideAssistance=!!protocol&&phase!=='prompted'
 useEffect(()=>{try{localStorage.setItem(KEY,JSON.stringify(saved))}catch{queueMicrotask(()=>setNotice('Local storage is full or unavailable. Export your evidence before closing.'))}},[saved])
 useEffect(()=>{let current=true;if(protocol)void evaluateLearning(protocol,saved.attempts.filter(a=>a.protocolId===protocol.id)).then(value=>{if(current)setScores(value)});return()=>{current=false}},[protocol,saved.attempts])
 useEffect(()=>()=>{if(replay)URL.revokeObjectURL(replay.url)},[replay])
 async function freeze(){try{const reviewed={...cue,review:{reviewer:reviewer.trim(),role:role.trim(),evidence:reviewEvidence.trim(),reviewedAt:new Date().toISOString()}};const next=await freezeLearningProtocol({schema:'singing-teacher/learning/1',id:crypto.randomUUID(),frozenAt:new Date().toISOString(),cue:reviewed,targetHz:Number(target),toleranceCents:Number(tolerance),context,phrase,retentionHours:Number(delay),minimumVoicedWindows:5,minimumVoicedFraction:.3,scoring:'median-absolute-cents/1',sessionId});setSaved(s=>({...s,protocol:next,protocolHistory:[...(s.protocolHistory??[]),next]}));setPhase('prompted');setNotice('Protocol frozen. Both cue wordings and scoring are now fixed.')}catch(e){setNotice(String(e))}}
 function start(){if(!protocol)return;try{recorder.current!.start();const next:LearningAttempt={reportFinalized:false,id:crypto.randomUUID(),protocolId:protocol.id,protocolDigest:protocol.digest,sessionId,arm,phase,startedAt:new Date().toISOString(),endedAt:'',deliveredWording:phase==='prompted'?(arm==='baseline'?protocol.cue.wording:protocol.cue.variant):'',contextConfirmed:confirmed,deviations,outcome:'completed',failureReason:null,recordingId:null,artifactId:null,artifactHash:null,filename:null,pitches:[],sensation:{provenance:'learner-self-report',words:'',bodyRegion:'',effort:0,discomfort:false,recognizable:false,confidence:0},mnemonic:''};setActive(next);setSaved(s=>({...s,pendingAttempt:next}));setWords('');setMnemonic('');setDiscomfort(false);setNotice('Recording this attempt. Stop when finished.')}catch(e){setNotice(String(e))}}
 function retainDraft(value:LearningAttempt){setDraft(value);setSaved(s=>({...s,pendingAttempt:value}))}
 async function stop(stopped=false){if(!active)return;setBusy(true);try{const recording=await recorder.current!.stop();const artifact=recording.observationBundle.artifacts[0];let pitches:LearningAttempt['pitches']=[];let failureReason:string|null=null;try{pitches=await extractLearningPitch(recording.blob)}catch{failureReason='Audio decoding failed; recording retained.'}await storeLearningMedia(recording.manifest.id,recording.blob);const interrupted=recording.manifest.stopReason!=='user';retainDraft({...active,startedAt:recording.manifest.startedAt,endedAt:recording.manifest.stoppedAt,recordingId:recording.manifest.id,artifactId:artifact?.id??null,artifactHash:artifact?.sha256??null,filename:recording.filename,pitches,outcome:stopped?'stopped':failureReason||interrupted?'failed':'completed',failureReason:stopped?'Stopped for discomfort / rest':failureReason??(interrupted?'Recording interrupted':null)});if(stopped)setDiscomfort(true);setNotice(stopped?'Stopped. Rest; save this attempt with your sensation report.':'Recording saved locally. Describe the attempt, then save.')}catch(e){retainDraft({...active,endedAt:new Date().toISOString(),outcome:'failed',failureReason:String(e)});setNotice('Capture failed; the failed attempt will be retained.')}finally{setActive(null);setBusy(false)}}
 async function exportEvidence(){const kit=await exportLearningInterchange([...(saved.protocolHistory??[]),...(protocol?[protocol]:[])],saved.attempts);download({schema:'singing-teacher/learning-export/1',...saved,scores,kit,media:'Download each attempt media separately. Stored locally in IndexedDB; no upload.'})}
 function saveAttempt(){if(!draft)return;const attempt={...draft,reportFinalized:true,sensation:{provenance:'learner-self-report' as const,words,bodyRegion:region,effort,discomfort,recognizable,confidence},mnemonic:hideAssistance?'':mnemonic};setSaved(s=>({...s,attempts:[...s.attempts,attempt],pendingAttempt:null,mnemonics:mnemonic&&!hideAssistance?{...s.mnemonics,[protocol!.cue.id]:mnemonic}:s.mnemonics}));setDraft(null);setNotice('Attempt retained, including failures. Sensations do not update anatomy.')}
 async function showReplay(attempt:LearningAttempt){if(!attempt.recordingId)return;try{const blob=await readLearningMedia(attempt.recordingId);if(!blob)throw Error('Media unavailable on this browser; use the separately downloaded recording.');setReplay({url:URL.createObjectURL(blob),filename:attempt.filename!})}catch(e){setNotice(String(e))}}
 const attempts=saved.attempts.filter(a=>a.protocolId===protocol?.id)
 return <section className="coach-learning" aria-label="Teaching and learning lab"><h3>Teaching & learning</h3><p>Compare two reviewed wordings, then test recall, phrase transfer and later retention. Measured pitch and subjective sensations stay separate from hidden anatomy.</p>
 {!protocol&&<><label>Candidate cue<select value={cue.id} onChange={e=>setCue(CUE_LIBRARY.find(c=>c.id===e.target.value)!)}>{CUE_LIBRARY.map(c=><option key={c.id} value={c.id}>{c.title} · review needed</option>)}</select></label><p><b>Fixed baseline:</b> {cue.wording}</p><p><b>Variant:</b> {cue.variant}</p><p>{cue.hypothesis}</p><p>{cue.evidenceLevel} <a href={cue.source} target="_blank" rel="noreferrer">Source</a></p><p>{REVIEW_ONLY_CANDIDATES}</p><details><summary>Record actual teacher / voice-specialist review</summary><p>No cue is preapproved. The reviewer must approve both exact wordings for this learner/context. This records a supplied review; it does not verify credentials.</p><label>Reviewer name<input value={reviewer} onChange={e=>setReviewer(e.target.value)}/></label><label>Reviewer role<input value={role} onChange={e=>setRole(e.target.value)}/></label><label>Review reference / notes<textarea value={reviewEvidence} onChange={e=>setReviewEvidence(e.target.value)}/></label></details><div className="coach-fields"><label>Comfortable target Hz<input type="number" value={target} onChange={e=>setTarget(e.target.value)}/></label><label>Tolerance cents<input type="number" value={tolerance} onChange={e=>setTolerance(e.target.value)}/></label><label>Context: vowel, level, posture<input value={context} onChange={e=>setContext(e.target.value)}/></label><label>Phrase on the same single note<input value={phrase} onChange={e=>setPhrase(e.target.value)}/></label><label>Retention delay hours<input type="number" min="1" value={delay} onChange={e=>setDelay(e.target.value)}/></label></div><button onClick={()=>void freeze()}>Freeze reviewed protocol</button></>}
 {protocol&&<><p>Frozen target {protocol.targetHz} Hz ± {protocol.toleranceCents} cents · {protocol.context}. Retention after {protocol.retentionHours} hours in a new browser session.</p><p>Review recorded: {protocol.cue.review?.reviewer}, {protocol.cue.review?.role}. Pitch is the only scored objective; movement agreement is unavailable.</p><div className="coach-fields"><label>Comparison arm<select disabled={!!active||!!draft} value={arm} onChange={e=>{setArm(e.target.value as LearningArm);try{localStorage.setItem(KEY+'-arm',e.target.value)}catch{/* Export remains available. */}}}><option value="baseline">Fixed baseline</option><option value="variant">Cue variant</option></select></label><label>Stage<select disabled={!!active||!!draft} value={phase} onChange={e=>{setPhase(e.target.value as LearningPhase);try{localStorage.setItem(KEY+'-phase',e.target.value)}catch{/* Export remains available. */}setConfirmed(false);setReplay(null)}}><option value="prompted">Prompted practice</option><option value="recall">Recall without cue</option><option value="transfer">Phrase transfer without cue</option><option value="retention">Later-session retention without cue</option></select></label></div>
 <div className="coach-action">{learningInstruction(protocol,arm,phase)}</div>
 {!hideAssistance&&<><p>What to notice: {protocol.cue.observable}</p><p>Your mnemonic: {saved.mnemonics[protocol.cue.id]||'None saved yet.'}</p><p>Alternatives: {protocol.cue.alternatives.join(' ')}</p></>}
 <p>{protocol.cue.stopRule}</p><label><input type="checkbox" disabled={!!active||!!draft} checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/> I will use the frozen context{phase==='transfer'?' with the declared phrase':''}.</label><label>Any deviations<input disabled={!!active||!!draft} value={deviations} onChange={e=>setDeviations(e.target.value)}/></label>
 <div className="coach-recorder"><RecordingControls controllerRef={recorder} videoStream={videoStream} audioStream={audioStream}/></div>
 {!draft&&<div className="coach-buttons"><button disabled={busy||(!active&&!confirmed)} onClick={()=>active?void stop():start()}>{busy?'Saving…':active?'Stop recording':'Start attempt recording'}</button>{active&&<button disabled={busy} onClick={()=>void stop(true)}>Stop · discomfort / rest</button>}</div>}
 {draft&&<fieldset><legend>Report this attempt</legend><label>Your sensation, in your words<textarea value={words} onChange={e=>setWords(e.target.value)}/></label><label>Body region (optional)<input value={region} onChange={e=>setRegion(e.target.value)}/></label><label>Effort 0–10<input type="range" min="0" max="10" value={effort} onChange={e=>setEffort(Number(e.target.value))}/>{effort}</label><label>Confidence in the report 0–5<input type="range" min="0" max="5" value={confidence} onChange={e=>setConfidence(Number(e.target.value))}/>{confidence}</label><label><input type="checkbox" checked={recognizable} onChange={e=>setRecognizable(e.target.checked)}/> I recognize this sensation</label><label><input type="checkbox" checked={discomfort} onChange={e=>setDiscomfort(e.target.checked)}/> Discomfort or strain</label>{!hideAssistance&&<label>Personal mnemonic to remember<input value={mnemonic} onChange={e=>setMnemonic(e.target.value)}/></label>}<label><input type="checkbox" checked={draft.outcome==='failed'} onChange={e=>setDraft({...draft,outcome:e.target.checked?'failed':'completed',failureReason:e.target.checked?'Learner reported unsuccessful execution':null})}/> Attempt unsuccessful</label><button onClick={saveAttempt}>Save attempt & sensation</button></fieldset>}
 <table><thead><tr><th>Stage</th><th>Fixed baseline</th><th>Variant</th></tr></thead><tbody>{compareLearning(attempts,scores).map(row=><tr key={row.phase}><td>{row.phase}</td>{row.arms.map(a=><td key={a.arm}>{a.passed}/{a.attempts} pass · {a.failed} failed · {a.excluded} excluded</td>)}</tr>)}</tbody></table><p>All attempts remain in the denominator. Results describe this pitch task, not teaching efficacy or physiological accuracy.</p>
 {!hideAssistance&&attempts.map(a=>{const score=scores.find(s=>s.attemptId===a.id);return <details key={a.id}><summary>{a.arm} · {a.phase} · {score?.status??'scoring'} · {score?.errorCents===null?'unscored':`${score?.errorCents?.toFixed(1)??'…'} cents error`}</summary><p>{score?.reasons.join('; ')}</p><p>Subjective sensation: {a.sensation.words||'No report'} · effort {a.sensation.effort}/10 · mnemonic: {a.mnemonic||'none'}</p><button disabled={!a.recordingId} onClick={()=>void showReplay(a)}>Replay / download attempt</button></details>})}
 </>}
 {replay&&!hideAssistance&&<div><video controls src={replay.url}/><a href={replay.url} download={replay.filename}>Download media</a><button onClick={()=>setReplay(null)}>Close replay</button></div>}
 <div className="coach-buttons"><button onClick={()=>void exportEvidence()}>Export protocol, reports & scores</button>{protocol&&!active&&!draft&&<button onClick={()=>{void exportEvidence().then(()=>{setSaved(s=>({...s,protocol:null}));setScores([])})}}>Export & start a new protocol</button>}</div><p role="status">{notice}</p>
 </section>
}
